version: '3'
services:
  tad:
    image: postgres:9.6
    container_name: postgres_training
    environment:
    - POSTGRES_DB=postgres
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=admin
    - TZ=GMT
    ports:
    - 5432:5432
  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: jaeger_training
    ports:
    - 5775:5775/udp
    - 6831:6831/udp
    - 6832:6832/udp
    - 5778:5778
    - 16686:16686
    - 14268:14268
    - 9411:9411
  app:
    image: felipe/training
    ports:
      - 8080:8080
    links:
      - tad
      - jaeger    